version: '3.8'

services:
  backend:
    build: ./mern-demo
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://s238178_db_user:pi3tjORU2glgq7iY@cluster0.hlusspf.mongodb.net/cloud_lab?retryWrites=true&w=majority

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend